default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

docker-base: &docker-base
  host: localhost
  username: postgres
  password: postgres
  port: 5432

development:
  <<: [*default, *docker-base]
  database: my_gpt_development

test:
  <<: [*default, *docker-base]
  database: my_gpt_test

production:
  url: <%= ENV['DATABASE_URL'] %>
